In [1]:
import numpy as np

In [2]:
import math

 NUMBER 4(a)

In [11]:
#inverse of the matrix (transpose)
matrix = [1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
matrix_invese = np.linalg.inv(matrix)
print(matrix_invese)


[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


number4(b)

In [5]:
#determinant of the matrix
matrix = [1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
determinant = np.linalg.det(matrix)
print(determinant)

0.2299999999999999


number 4(c)

In [7]:
#(C) Decompose the matrix
matrix = [1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)

[2.04100779 0.82188052 0.13711169]


number 4(d)

In [8]:
# (d) Transform (multiply by a scalar)
scalar = 2
transformed_matrix = scalar * matrix
print(transformed_matrix)

[[2.  0.4 1. ]
 [0.4 2.  1.6]
 [1.  1.6 2. ]]
