In [2]:
import numpy as np

In [4]:
import math

In [8]:
# 2x + M - C = 6
# -5x - Z + 2z = -12
# -2x + y + 2z = 4

coefficients = [[2, 1, -1],[-5, -1, 2],[-2, 1, 2]]
constants = ([6, 12, 4])


coefficients =np.array([[2, 1, -1],[-5, -1, 2],[-2, 1, 2]])
constants = np.array([6, 12, 4])


solution =np.linalg.solve(coefficients, constants)
print(solution)



[-11.2  12.8 -15.6]


adding three linear equations

In [11]:
# 2x + M - C = 6
# -5x - Z + 2z = -12
# -2x + y + 2z = 4

coefficients = [[2, 1, -1],[-5, -1, 2],[-2, 1, 2]]
constants = ([6, 12, 4])


coefficients =np.array([[2, 1, -1],[-5, -1, 2],[-2, 1, 2]])
constants = np.array([6, 12, 4])
result =np.add(coefficients, constants)
print(result)

[[ 8 13  3]
 [ 1 11  6]
 [ 4 13  6]]
